const TransactionDAO = require('../DAO/transactionDAO');
const Transaction = require('../models/transaction');

class TransactionService {
    async processTransaction(cardNumber, pin, transactionType, transactionAmount) {

        console.log(cardNumber + "\t" + pin + "\t" + transactionType + "\t" + transactionAmount);
        // Get customer details using the card number
        const customer = await TransactionDAO.getCustomerByCardNumber(cardNumber);
    
        console.log(customer);
        if (!customer) {
            throw new Error('Customer not found.');
        }

        // Verify the PIN
        const isPinValid = await TransactionDAO.verifyPin(customer.CustID_Nr, pin);
        if (!isPinValid) {
            throw new Error('Invalid PIN.');
        }

        // Create a new transaction
        const transaction = new Transaction(
            null, // TransactionID will be generated by the database
            customer.AccountID,
            transactionType,
            new Date(),
            transactionAmount,
            'Pending', // Initial status
            false, // IsPanicTriggered
            null // LocationID can be added if necessary
        );

        const transactionID = await TransactionDAO.createTransaction(transaction);
        return transactionID; // Return the ID of the newly created transaction
    }
}

module.exports = new TransactionService();
